version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/src/fullcircl-desktop-client/web-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/fullcircl-desktop-client"
    schedule:
      interval: "weekly"